from PyQt5 import QtCore, QtGui, QtWidgets

class Calc_UI(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Calculator by Fer")
        Dialog.resize(581, 296)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 130, 320, 112))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.num_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.num_3.setObjectName("num_3")
        self.gridLayout.addWidget(self.num_3, 2, 2, 1, 1)
        self.num_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.num_0.setObjectName("num_0")
        self.gridLayout.addWidget(self.num_0, 3, 1, 1, 1)
        self.num_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.num_9.setObjectName("num_9")
        self.gridLayout.addWidget(self.num_9, 0, 2, 1, 1)
        self.num_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.num_5.setObjectName("num_5")
        self.gridLayout.addWidget(self.num_5, 1, 1, 1, 1)
        self.num_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.num_4.setObjectName("num_4")
        self.gridLayout.addWidget(self.num_4, 1, 0, 1, 1)
        self.num_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.num_1.setObjectName("num_1")
        self.gridLayout.addWidget(self.num_1, 2, 0, 1, 1)
        self.num_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.num_8.setObjectName("num_8")
        self.gridLayout.addWidget(self.num_8, 0, 1, 1, 1)
        self.num_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.num_7.setObjectName("num_7")
        self.gridLayout.addWidget(self.num_7, 0, 0, 1, 1)
        self.num_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.num_6.setObjectName("num_6")
        self.gridLayout.addWidget(self.num_6, 1, 2, 1, 1)
        self.num_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.num_2.setObjectName("num_2")
        self.gridLayout.addWidget(self.num_2, 2, 1, 1, 1)
        self.dot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.dot.setObjectName("dot")
        self.gridLayout.addWidget(self.dot, 3, 0, 1, 1)
        self.btn_delete = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_delete.setObjectName("btn_delete")
        self.gridLayout.addWidget(self.btn_delete, 3, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(370, 110, 160, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_sum = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_sum.setObjectName("btn_sum")
        self.gridLayout_2.addWidget(self.btn_sum, 0, 0, 1, 1)
        self.btn_result = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_result.setObjectName("btn_result")
        self.gridLayout_2.addWidget(self.btn_result, 6, 0, 1, 1)
        self.btn_mult = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_mult.setObjectName("btn_mult")
        self.gridLayout_2.addWidget(self.btn_mult, 2, 0, 1, 1)
        self.btn_div = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_div.setObjectName("btn_div")
        self.gridLayout_2.addWidget(self.btn_div, 3, 0, 1, 1)
        self.btn_subs = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_subs.setObjectName("btn_subs")
        self.gridLayout_2.addWidget(self.btn_subs, 1, 0, 1, 1)
        self.display = QtWidgets.QLCDNumber(Dialog)
        self.display.setGeometry(QtCore.QRect(50, 20, 481, 71))
        self.display.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.display.setObjectName("display")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Calculator by Fer", "Calculator by Fer"))
        self.num_3.setText(_translate("Dialog", "3"))
        self.num_0.setText(_translate("Dialog", "0"))
        self.num_9.setText(_translate("Dialog", "9"))
        self.num_5.setText(_translate("Dialog", "5"))
        self.num_4.setText(_translate("Dialog", "4"))
        self.num_1.setText(_translate("Dialog", "1"))
        self.num_8.setText(_translate("Dialog", "8"))
        self.num_7.setText(_translate("Dialog", "7"))
        self.num_6.setText(_translate("Dialog", "6"))
        self.num_2.setText(_translate("Dialog", "2"))
        self.dot.setText(_translate("Dialog", "."))
        self.btn_delete.setText(_translate("Dialog", "DEL"))
        self.btn_sum.setText(_translate("Dialog", "+"))
        self.btn_result.setText(_translate("Dialog", "="))
        self.btn_mult.setText(_translate("Dialog", "*"))
        self.btn_div.setText(_translate("Dialog", "/"))
        self.btn_subs.setText(_translate("Dialog", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Calc_UI()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
